language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
notifications:
  email: false
script:
- npm install
- npm run build
after_success:
- bash ./tasks/deploy.sh
after_failure:
- bash ./tasks/failed.sh
env:
  global:
  - GH_USER: javaBin
  - GH_REPO_PROD: javazone-2018-prod
  - GH_REPO_TEST: javazone-2018-test
  - secure: MY6mKG4rpg7Ug2ZOP9WreNzCLrQ6GRwXtVjtOq9GthcOZEslXIPrlZQZp6FaolUawd2MWspYXtRK60pit+AIHkGF/5Qt18vDzRm77xb2Bq+jqMmsea9GCB2uu8KimiV+RtCbxajpe9YAXXuYqc1wLBi+GfikWUzKtz1+1fN8+Oc3vNNGr3UJfF13IIIhRr+7n8oPKnbxNkj/5dTeazErPK29HJpREjO+7G+N8dQD2JbRCfL4vXRh6kpMCO77N/Xx6v7l67nzipJ4RK4m1QKbP2+rQswfa35m7v/ZlH7dD1kRhECUq6aoO4zsoswVdK2jZ3fAFD4zRYaYPbImzEy87DSb8DtXk9mwlyHey+tFPUIQr1/QPS4jvKTE0EinEFMe4FORFd5H1WBmmeVfCpmfUTiqvM1SCBX9zyCIUfZr5JaBnhYJIb3OztUBVtdMpG9Ln+uMYlBtaLjrsVaeWUHvS1cig6mFlHrWhphdr05Koda1Lj9PWJGylBRnTLyDJ8R0DQm34vgewdaXdoNR600v+0uDZqpAM1Y/EIlRVaIXdEfnuYtAys66VfTr9WJT4/y7gtZvBlf8UeU0xiSqDjDy5Ofw0kcThVLAYepsvFCTiCiNpJ7yiw49kkh7SkQpi3eWx0asvVfOCfUGOS/N14VotOOlkwbfg7HOKgsk1BTF4qU=
  - secure: FPgaT9FQNKl/coAKutgpQdo+JeCz4af2bw0eCD46v+cELQcmFTVoOPJKtVl3A4pS8S4g+GcTRTfMCj3TteKQ7nnMaoJpVbjF+gxrqtPU2BNbKdsYGtHL8Cv/Y5uYYM/hMM5Y1Su3Z9BmbGfa8oIXfayKF/5hLAqVMpkRdQkxscDQL+Shk3g0p7fSMhYuVVwA8YUBKbt5nd2mH0XFBYMWjSYA21LyrB8NVQxx9gZNHYQv0+LpC+Ki480jpYatr4wyJ2+slksFEVvGM2rTPfn+hAQQGuWe+LHTgvcwFFLxs1razY7bZusup++1137l7XwR9Yi3cT0OBhEtUeankhSHvVH+k4Dydh8Sq7QPp8XMCUx2pqseCHEOf/GKnoAbdkr/8VqEdRVFmNwxQpKnxnlL0SNwB32VuFKry824eTWfqeHkH6kmL6eZErcNecAe97N1nxDU45c5h6eeUIqGAjujbUED4LrbCKxBi3yZ/ZedWCIDty59aXYACbkv7bln1xRWxZenIl/jQ6cfSa6MHBnEno99vJyL1eMN0TchGFUvTIV0hxVfCpjqXZuqY8MbBwcA6FhINUgF1I0Hq2pI+kps1xCfGV2IwI0jmDFKiDUlzSRCNRyt+jq83LflmBydOug1qeupu1hGjAT1juzJX5FxqxzcPmOojWjmY7N5FEu3pUo=
  - secure: Hgl8ZK5Bg/DiE6QdYSs68myrn9AKjc91ehI0K+vtdocFDXZjCCocNRmCDur/O+SFBDDy4cTw0j/AMwosilmrH1qwnBLy/AriJ9bd1TwwOSUSpkSLLsDGqxoszps1EOrGpCCiCG5eVZf1pNVuT1fc+pplA01vhWdG6emOMvh51hw+FtPo4uB/KHnxKcH755XjAidHWgZY219x/8wb4LDMRWK0ZJQ3p2QcJwV2bNfBqanzNgwdCjKFB2LaA7NtFloy1NmZinMO9M+H8cK0Y3/23vLqyy3ASOJ5j66MP2P4imUH7QgEKTUrHWwszbS25UmK9/xkPZgSnM3MS0wpfM/MQQjua021EUvF3Mu/u4LXKcO7ohqmKGZnJLOULry81Ms0oEuyJpziMQpMAy3QK/hMLA8TWqLrYlVnlz0SMR/SMlCxPtq/cvjqP1mA7HMUuTZOix0KAPWSZjZTmdJrcdU5QVVEEWeFhOpI/9CWXotCLHquQM/hoYn8HfjdtgW3200j8tYT/Y5Gr/ylAu1wk3udOMHowmq0GSopJGHdmM7M5WBcehZHe1ZQMHooC2+eN7Xhz3hF9NKW0ajkDDLTeDvxTEwLYLaRt21dQzl2l/INsFoa+92WLAdopmsa0pSVsgUWknrnWQwLhtwuOSHZngqIXYdhwFbgaWNIzRZXKkQiaP8=
